//=====================================================
// ** pipeVertexData.js
//-----------------------------------------------------
// Defines all data points
//=====================================================
const pipeVertexData = {
    // Data points on pipes
    "j1": {"use": true, "coor": [517, -105], "speed": null, "temperature": null, "pressure": null},
    "j3": {"use": true, "coor": [517, -10], "speed": null, "temperature": null, "pressure": null},
    "j4": {"use": true, "coor": [821, -10], "speed": null, "temperature": null, "pressure": null},
    "j6": {"use": true, "coor": [820, -104], "speed": null, "temperature": null, "pressure": null},
    "j7": {"use": true, "coor": [1096, -10], "speed": null, "temperature": null, "pressure": null},
    "j9": {"use": true, "coor": [1096, -107], "speed": null, "temperature": null, "pressure": null},
    "j10": {"use": true, "coor": [1157, 15], "speed": null, "temperature": null, "pressure": null},
    "j11": {"use": true, "coor": [582, 15], "speed": null, "temperature": null, "pressure": null},
    "j12": {"use": true, "coor": [582, 231], "speed": null, "temperature": null, "pressure": null},
    "j13": {"use": true, "coor": [833, 231], "speed": null, "temperature": null, "pressure": null},
    "j14": {"use": true, "coor": [1211, -100], "speed": null, "temperature": null, "pressure": null},
    "j15": {"use": true, "coor": [1210, 40], "speed": null, "temperature": null, "pressure": null},
    "j16": {"use": true, "coor": [596, 40], "speed": null, "temperature": null, "pressure": null},
    "j17": {"use": true, "coor": [596, 110], "speed": null, "temperature": null, "pressure": null},
    "j18": {"use": true, "coor": [596, 196], "speed": null, "temperature": null, "pressure": null},
    "j20": {"use": true, "coor": [795, 195], "speed": null, "temperature": null, "pressure": null},
    "j21": {"use": true, "coor": [910, 195], "speed": null, "temperature": null, "pressure": null},
    "j22": {"use": true, "coor": [939, 195], "speed": null, "temperature": null, "pressure": null},
    "j23": {"use": true, "coor": [1224, -70], "speed": null, "temperature": null, "pressure": null},
    "j24": {"use": true, "coor": [1224, 105], "speed": null, "temperature": null, "pressure": null},
    "j25_1": {"use": true, "coor": [1224, 135], "speed": null, "temperature": null, "pressure": null},
    "j25_2": {"use": true, "coor": [1202, 135], "speed": null, "temperature": null, "pressure": null},
    "j26": {"use": true, "coor": [1202, 189], "speed": null, "temperature": null, "pressure": null},
    "j27": {"use": true, "coor": [975, 189], "speed": null, "temperature": null, "pressure": null},
    "j28": {"use": true, "coor": [975, 224], "speed": null, "temperature": null, "pressure": null},
    "j29": {"use": true, "coor": [890, 224], "speed": null, "temperature": null, "pressure": null},
    "j30": {"use": true, "coor": [890, 450], "speed": null, "temperature": null, "pressure": null},
    "j33": {"use": true, "coor": [890, 519], "speed": null, "temperature": null, "pressure": null},
    "j34": {"use": true, "coor": [930, 519], "speed": null, "temperature": null, "pressure": null},
    "j35": {"use": true, "coor": [945, 543], "speed": null, "temperature": null, "pressure": null},
    "j36": {"use": true, "coor": [828, 640], "speed": null, "temperature": null, "pressure": null},
    "j37": {"use": true, "coor": [910, 640], "speed": null, "temperature": null, "pressure": null},
    "j38": {"use": true, "coor": [875, 380], "speed": null, "temperature": null, "pressure": null},
    "j39": {"use": true, "coor": [875, 270], "speed": null, "temperature": null, "pressure": null},
    "j40": {"use": true, "coor": [1380, 270], "speed": null, "temperature": null, "pressure": null},
    "j41": {"use": true, "coor": [1380, 111], "speed": null, "temperature": null, "pressure": null},
    "j42": {"use": true, "coor": [559, 129], "speed": null, "temperature": null, "pressure": null},
    "j43": {"use": true, "coor": [559, 741], "speed": null, "temperature": null, "pressure": null},
    "j46": {"use": true, "coor": [517, 638], "speed": null, "temperature": null, "pressure": null},
    "j47": {"use": true, "coor": [632, 638], "speed": null, "temperature": null, "pressure": null},
    "j48": {"use": true, "coor": [665, 638], "speed": null, "temperature": null, "pressure": null},
    "j49": {"use": true, "coor": [698, 638], "speed": null, "temperature": null, "pressure": null},
    "j50": {"use": true, "coor": [731, 638], "speed": null, "temperature": null, "pressure": null},
    "j51": {"use": true, "coor": [763, 638], "speed": null, "temperature": null, "pressure": null},
    "j52": {"use": true, "coor": [1100, 943], "speed": null, "temperature": null, "pressure": null},
    "j53": {"use": true, "coor": [1030, 1016], "speed": null, "temperature": null, "pressure": null},
    "j55": {"use": true, "coor": [866, 1016], "speed": null, "temperature": null, "pressure": null},
    "j56": {"use": true, "coor": [866, 990], "speed": null, "temperature": null, "pressure": null},
    "j59": {"use": true, "coor": [1000, 989], "speed": null, "temperature": null, "pressure": null},

    // Data points attached to blocks
    "input1_1": {"use": true, "coor": [587, -105], "speed": null, "temperature": null, "pressure": null},
    "output1_1": {"use": true, "coor": [784, -105], "speed": null, "temperature": null, "pressure": null},
    "input2_1": {"use": true, "coor": [877, -105], "speed": null, "temperature": null, "pressure": null},
    "output2_1": {"use": true, "coor": [1074, -105], "speed": null, "temperature": null, "pressure": null},
    "input3_1": {"use": true, "coor": [1147, -105], "speed": null, "temperature": null, "pressure": null},
    "input3_2": {"use": true, "coor": [1157, -58], "speed": null, "temperature": null, "pressure": null},
    "output3_1": {"use": true, "coor": [1189, -122], "speed": null, "temperature": null, "pressure": null},
    "input5_1": {"use": true, "coor": [1365, 111], "speed": null, "temperature": null, "pressure": null},
    "output5_1": {"use": true, "coor": [1330, 56], "speed": null, "temperature": null, "pressure": null},
    "input6_1": {"use": true, "coor": [1257, -122], "speed": null, "temperature": null, "pressure": null},
    "input6_2": {"use": true, "coor": [1330, -58], "speed": null, "temperature": null, "pressure": null},
    "output6_1": {"use": true, "coor": [1257, -101], "speed": null, "temperature": null, "pressure": null},
    "output6_2": {"use": true, "coor": [1257, -70], "speed": null, "temperature": null, "pressure": null},
    "input7_1": {"use": true, "coor": [610, 110], "speed": null, "temperature": null, "pressure": null},
    "input7_2": {"use": true, "coor": [1183, 105], "speed": null, "temperature": null, "pressure": null},
    "output7_1": {"use": true, "coor": [610, 129], "speed": null, "temperature": null, "pressure": null},
    "output7_2": {"use": true, "coor": [939, 178], "speed": null, "temperature": null, "pressure": null},
    "output7_3": {"use": true, "coor": [975, 178], "speed": null, "temperature": null, "pressure": null},
    "input13_1": {"use": true, "coor": [615, 741], "speed": null, "temperature": null, "pressure": null},
    "input13_2": {"use": true, "coor": [750, 875], "speed": null, "temperature": null, "pressure": null},
    "output13_1": {"use": true, "coor": [632, 676], "speed": null, "temperature": null, "pressure": null},
    "output13_2": {"use": true, "coor": [665, 676], "speed": null, "temperature": null, "pressure": null},
    "output13_3": {"use": true, "coor": [699, 676], "speed": null, "temperature": null, "pressure": null},
    "output13_4": {"use": true, "coor": [731, 676], "speed": null, "temperature": null, "pressure": null},
    "output13_5": {"use": true, "coor": [763, 676], "speed": null, "temperature": null, "pressure": null},
    "input15_1": {"use": true, "coor": [795, 370], "speed": null, "temperature": null, "pressure": null},
    "output15_1": {"use": true, "coor": [833, 370], "speed": null, "temperature": null, "pressure": null},
    "output15_2": {"use": true, "coor": [857, 380], "speed": null, "temperature": null, "pressure": null},
    "output15_3": {"use": true, "coor": [857, 450], "speed": null, "temperature": null, "pressure": null},
    "output15_4": {"use": true, "coor": [857, 519], "speed": null, "temperature": null, "pressure": null},
    "output15_5": {"use": true, "coor": [828, 600], "speed": null, "temperature": null, "pressure": null},
    "input17_1": {"use": true, "coor": [828, 676], "speed": null, "temperature": null, "pressure": null},
    "input17_2": {"use": true, "coor": [945, 676], "speed": null, "temperature": null, "pressure": null},
    "output17_1": {"use": true, "coor": [1000, 875], "speed": null, "temperature": null, "pressure": null},
    "output17_2": {"use": true, "coor": [1100, 875], "speed": null, "temperature": null, "pressure": null},


};

